version: "3.3"

services:

  nginx:
    image: iamtrungbui/docker-nginx:latest
    container_name: lar_app_nginx
    ports:
      - "${APP_PORT}:80"
      - "443:443"
    links:
      - php
      - db
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      # - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx
      - ./etc/nginx/ssl/:/etc/nginx/ssl
    networks:
      - lar_app_network
    environment:
      - EXTRA_HOST=${EXTRA_HOST}
    extra_hosts:
      - "${EXTRA_HOST}:127.0.0.1"

  php:
    image: iamtrungbui/docker-php-fpm:latest
    container_name: lar_app_php_7
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - lar_app_network

  db:
    image: mariadb
    container_name: lar_app_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
    - ./data/db:/var/lib/mysql
    ports:
    - "${DB_PORT}:3306"

networks:
  lar_app_network:
    driver: "bridge"

volumes:
    nginx_db_data:
